Update reusable-maven-build.yml

diff --git a/.github/workflows/reusable-maven-build.yml b/.github/workflows/reusable-maven-build.yml
--- a/.github/workflows/reusable-maven-build.yml
+++ b/.github/workflows/reusable-maven-build.yml
@@ -55,8 +55,12 @@ jobs:
         
       - name: Upload JAR to S3
         run: |
-           if [ "${{ inputs.environment }}" == "dev" ] || ["${{ inputs.environment }}" == "test" ]; then
+           if [ "${{ inputs.environment }}" == "dev" ] || [ "${{ inputs.environment }}" == "test" ]; then
              aws s3 cp target/*.jar s3://${{ vars.S3_BUCKET_DEV_TEST }}/${{ inputs.environment }}/
            elif [ "${{ inputs.environment }}" == "prod" ]; then
-             aws s3 cp target/*.jar s3://$${{ vars.S3_BUCKET_PROD }}/${{ inputs.environment }}/
+             aws s3 cp target/*.jar s3://${{ vars.S3_BUCKET_PROD }}/${{ inputs.environment }}/
+           else
+            echo "Invalid environment: ${{ inputs.environment }}"
+            exit 1
+           fi
            fi
